// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Customer struct {
	ID    int32
	Name  string
	Email string
}

type Order struct {
	ID          int32
	CustomerID  int32
	ProductID   int32
	UnitsAmount int32
	UnitPrice   int32
	CreatedAt   sql.NullTime
}

type Product struct {
	ID    int32
	Name  string
	Price int32
	Stock int32
}
